// <auto-generated />
using System;
using FitMetrics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitMetrics.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604193246_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitMetrics.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CaloriesBurnedPerMinute")
                        .HasColumnType("float");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesBurnedPerMinute = 6.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 2,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            CaloriesBurnedPerMinute = 6.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 2,
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = 3,
                            CaloriesBurnedPerMinute = 7.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 2,
                            Name = "Şınav (Push-up)"
                        },
                        new
                        {
                            Id = 4,
                            CaloriesBurnedPerMinute = 8.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 3,
                            Name = "Barfiks (Pull-up)"
                        },
                        new
                        {
                            Id = 5,
                            CaloriesBurnedPerMinute = 6.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 3,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 6,
                            CaloriesBurnedPerMinute = 6.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 3,
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 7,
                            CaloriesBurnedPerMinute = 9.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 3,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 8,
                            CaloriesBurnedPerMinute = 8.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 4,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 9,
                            CaloriesBurnedPerMinute = 7.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 4,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 10,
                            CaloriesBurnedPerMinute = 7.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 4,
                            Name = "Lunge"
                        },
                        new
                        {
                            Id = 11,
                            CaloriesBurnedPerMinute = 5.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 4,
                            Name = "Leg Curl"
                        },
                        new
                        {
                            Id = 12,
                            CaloriesBurnedPerMinute = 6.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 5,
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 13,
                            CaloriesBurnedPerMinute = 4.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 5,
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            Id = 14,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 6,
                            Name = "Biceps Curl"
                        },
                        new
                        {
                            Id = 15,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 6,
                            Name = "Triceps Pushdown"
                        },
                        new
                        {
                            Id = 16,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 7,
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 17,
                            CaloriesBurnedPerMinute = 4.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 7,
                            Name = "Mekik (Crunch)"
                        },
                        new
                        {
                            Id = 18,
                            CaloriesBurnedPerMinute = 11.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Koşu"
                        },
                        new
                        {
                            Id = 19,
                            CaloriesBurnedPerMinute = 9.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Bisiklet"
                        },
                        new
                        {
                            Id = 20,
                            CaloriesBurnedPerMinute = 10.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Kürek (Rowing)"
                        },
                        new
                        {
                            Id = 21,
                            CaloriesBurnedPerMinute = 12.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "İp Atlama"
                        },
                        new
                        {
                            Id = 22,
                            CaloriesBurnedPerMinute = 5.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Yürüyüş"
                        },
                        new
                        {
                            Id = 23,
                            CaloriesBurnedPerMinute = 10.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Yüzme"
                        },
                        new
                        {
                            Id = 24,
                            CaloriesBurnedPerMinute = 8.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Eliptik"
                        });
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("CaloriesPer100g")
                        .HasColumnType("float");

                    b.Property<double>("CarbsPer100g")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("FatPer100g")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("ProteinPer100g")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPer100g = 165.0,
                            CarbsPer100g = 0.0,
                            Category = "Protein",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3.6000000000000001,
                            Name = "Tavuk Göğsü (Izgara)",
                            ProteinPer100g = 31.0
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPer100g = 155.0,
                            CarbsPer100g = 1.1000000000000001,
                            Category = "Protein",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 11.0,
                            Name = "Yumurta (Tam)",
                            ProteinPer100g = 13.0
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPer100g = 389.0,
                            CarbsPer100g = 66.0,
                            Category = "Tahıl",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 6.9000000000000004,
                            Name = "Yulaf Ezmesi",
                            ProteinPer100g = 16.899999999999999
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPer100g = 130.0,
                            CarbsPer100g = 28.0,
                            Category = "Tahıl",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.29999999999999999,
                            Name = "Beyaz Pirinç (Pişmiş)",
                            ProteinPer100g = 2.7000000000000002
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPer100g = 247.0,
                            CarbsPer100g = 41.0,
                            Category = "Tahıl",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3.3999999999999999,
                            Name = "Tam Buğday Ekmeği",
                            ProteinPer100g = 13.0
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPer100g = 89.0,
                            CarbsPer100g = 23.0,
                            Category = "Meyve",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.29999999999999999,
                            Name = "Muz",
                            ProteinPer100g = 1.1000000000000001
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPer100g = 52.0,
                            CarbsPer100g = 14.0,
                            Category = "Meyve",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.20000000000000001,
                            Name = "Elma",
                            ProteinPer100g = 0.29999999999999999
                        },
                        new
                        {
                            Id = 8,
                            CaloriesPer100g = 579.0,
                            CarbsPer100g = 22.0,
                            Category = "Kuruyemiş",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 50.0,
                            Name = "Badem",
                            ProteinPer100g = 21.0
                        },
                        new
                        {
                            Id = 9,
                            CaloriesPer100g = 654.0,
                            CarbsPer100g = 14.0,
                            Category = "Kuruyemiş",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 65.0,
                            Name = "Ceviz",
                            ProteinPer100g = 15.0
                        },
                        new
                        {
                            Id = 10,
                            CaloriesPer100g = 50.0,
                            CarbsPer100g = 5.0,
                            Category = "Süt Ürünü",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 1.8,
                            Name = "Süt (Yarım Yağlı)",
                            ProteinPer100g = 3.3999999999999999
                        },
                        new
                        {
                            Id = 11,
                            CaloriesPer100g = 61.0,
                            CarbsPer100g = 4.7000000000000002,
                            Category = "Süt Ürünü",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3.2999999999999998,
                            Name = "Yoğurt (Tam Yağlı)",
                            ProteinPer100g = 3.5
                        },
                        new
                        {
                            Id = 12,
                            CaloriesPer100g = 98.0,
                            CarbsPer100g = 3.3999999999999999,
                            Category = "Süt Ürünü",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 4.2999999999999998,
                            Name = "Lor Peyniri",
                            ProteinPer100g = 11.0
                        },
                        new
                        {
                            Id = 13,
                            CaloriesPer100g = 208.0,
                            CarbsPer100g = 0.0,
                            Category = "Protein",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 13.0,
                            Name = "Somon (Izgara)",
                            ProteinPer100g = 20.0
                        },
                        new
                        {
                            Id = 14,
                            CaloriesPer100g = 116.0,
                            CarbsPer100g = 0.0,
                            Category = "Protein",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 1.0,
                            Name = "Ton Balığı (Suda)",
                            ProteinPer100g = 26.0
                        },
                        new
                        {
                            Id = 15,
                            CaloriesPer100g = 250.0,
                            CarbsPer100g = 0.0,
                            Category = "Protein",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 15.0,
                            Name = "Dana Eti (Yağsız)",
                            ProteinPer100g = 26.0
                        },
                        new
                        {
                            Id = 16,
                            CaloriesPer100g = 116.0,
                            CarbsPer100g = 20.0,
                            Category = "Baklagil",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.40000000000000002,
                            Name = "Mercimek (Pişmiş)",
                            ProteinPer100g = 9.0
                        },
                        new
                        {
                            Id = 17,
                            CaloriesPer100g = 164.0,
                            CarbsPer100g = 27.0,
                            Category = "Baklagil",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 2.6000000000000001,
                            Name = "Nohut (Pişmiş)",
                            ProteinPer100g = 8.9000000000000004
                        },
                        new
                        {
                            Id = 18,
                            CaloriesPer100g = 34.0,
                            CarbsPer100g = 7.0,
                            Category = "Sebze",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.40000000000000002,
                            Name = "Brokoli",
                            ProteinPer100g = 2.7999999999999998
                        },
                        new
                        {
                            Id = 19,
                            CaloriesPer100g = 87.0,
                            CarbsPer100g = 20.0,
                            Category = "Sebze",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.10000000000000001,
                            Name = "Patates (Haşlanmış)",
                            ProteinPer100g = 1.8999999999999999
                        },
                        new
                        {
                            Id = 20,
                            CaloriesPer100g = 86.0,
                            CarbsPer100g = 20.0,
                            Category = "Sebze",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.10000000000000001,
                            Name = "Tatlı Patates",
                            ProteinPer100g = 1.6000000000000001
                        },
                        new
                        {
                            Id = 21,
                            CaloriesPer100g = 400.0,
                            CarbsPer100g = 8.0,
                            Category = "Takviye",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 6.0,
                            Name = "Whey Protein Tozu",
                            ProteinPer100g = 80.0
                        },
                        new
                        {
                            Id = 22,
                            CaloriesPer100g = 884.0,
                            CarbsPer100g = 0.0,
                            Category = "Yağ",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 100.0,
                            Name = "Zeytinyağı",
                            ProteinPer100g = 0.0
                        },
                        new
                        {
                            Id = 23,
                            CaloriesPer100g = 160.0,
                            CarbsPer100g = 9.0,
                            Category = "Meyve",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 15.0,
                            Name = "Avokado",
                            ProteinPer100g = 2.0
                        },
                        new
                        {
                            Id = 24,
                            CaloriesPer100g = 304.0,
                            CarbsPer100g = 82.0,
                            Category = "Tatlandırıcı",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.0,
                            Name = "Bal",
                            ProteinPer100g = 0.29999999999999999
                        },
                        new
                        {
                            Id = 25,
                            CaloriesPer100g = 131.0,
                            CarbsPer100g = 25.0,
                            Category = "Tahıl",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 1.1000000000000001,
                            Name = "Makarna (Pişmiş)",
                            ProteinPer100g = 5.0
                        },
                        new
                        {
                            Id = 26,
                            CaloriesPer100g = 209.0,
                            CarbsPer100g = 0.0,
                            Category = "Protein",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 11.0,
                            Name = "Tavuk But",
                            ProteinPer100g = 26.0
                        },
                        new
                        {
                            Id = 27,
                            CaloriesPer100g = 264.0,
                            CarbsPer100g = 2.0,
                            Category = "Süt Ürünü",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 21.0,
                            Name = "Beyaz Peynir",
                            ProteinPer100g = 17.0
                        },
                        new
                        {
                            Id = 28,
                            CaloriesPer100g = 83.0,
                            CarbsPer100g = 19.0,
                            Category = "Tahıl",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.20000000000000001,
                            Name = "Bulgur (Pişmiş)",
                            ProteinPer100g = 3.0
                        },
                        new
                        {
                            Id = 29,
                            CaloriesPer100g = 135.0,
                            CarbsPer100g = 0.0,
                            Category = "Protein",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 1.0,
                            Name = "Hindi Göğsü",
                            ProteinPer100g = 30.0
                        },
                        new
                        {
                            Id = 30,
                            CaloriesPer100g = 546.0,
                            CarbsPer100g = 61.0,
                            Category = "Atıştırmalık",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 31.0,
                            Name = "Bitter Çikolata",
                            ProteinPer100g = 4.9000000000000004
                        });
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.NutritionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmountGrams")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId", "LoggedAt");

                    b.ToTable("NutritionLogs");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentWeightKg")
                        .HasColumnType("float");

                    b.Property<int>("DailyCalorieGoal")
                        .HasColumnType("int");

                    b.Property<int>("DailyProteinGoal")
                        .HasColumnType("int");

                    b.Property<int>("DailyWaterGoalMl")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("GoalType")
                        .HasColumnType("int");

                    b.Property<double>("HeightCm")
                        .HasColumnType("float");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("TargetWeightKg")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WeightEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("WeightEntries");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CaloriesBurned")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId", "PerformedAt");

                    b.ToTable("WorkoutLogs");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.NutritionLog", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.Food", "Food")
                        .WithMany("NutritionLogs")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitMetrics.Domain.Entities.User", "User")
                        .WithMany("NutritionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WeightEntry", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.User", "User")
                        .WithMany("WeightEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutLog", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.Exercise", "Exercise")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitMetrics.Domain.Entities.User", "User")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("WorkoutLogs");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.Food", b =>
                {
                    b.Navigation("NutritionLogs");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.User", b =>
                {
                    b.Navigation("NutritionLogs");

                    b.Navigation("WeightEntries");

                    b.Navigation("WorkoutLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
