// <auto-generated />
using System;
using FitMetrics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitMetrics.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612171607_AddBodyMeasurements")]
    partial class AddBodyMeasurements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitMetrics.Domain.Entities.BodyMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ArmCm")
                        .HasColumnType("float");

                    b.Property<double?>("ChestCm")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("HipCm")
                        .HasColumnType("float");

                    b.Property<double?>("NeckCm")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double?>("WaistCm")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BodyMeasurements");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.DietitianClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DietitianId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietitianId", "ClientId")
                        .IsUnique();

                    b.ToTable("DietitianClients");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CaloriesBurnedPerMinute")
                        .HasColumnType("float");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesBurnedPerMinute = 6.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 2,
                            Name = "Bench Press (Barbell)"
                        },
                        new
                        {
                            Id = 2,
                            CaloriesBurnedPerMinute = 6.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 2,
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = 3,
                            CaloriesBurnedPerMinute = 7.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 2,
                            Name = "Push-Up (Şınav)"
                        },
                        new
                        {
                            Id = 25,
                            CaloriesBurnedPerMinute = 5.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 2,
                            Name = "Chest Fly (Dumbbell / Cable)"
                        },
                        new
                        {
                            Id = 26,
                            CaloriesBurnedPerMinute = 7.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 2,
                            Name = "Dips (Göğüs Odaklı)"
                        },
                        new
                        {
                            Id = 27,
                            CaloriesBurnedPerMinute = 6.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 2,
                            Name = "Decline Press (Ters Eğimli)"
                        },
                        new
                        {
                            Id = 7,
                            CaloriesBurnedPerMinute = 9.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 3,
                            Name = "Deadlift (Barbell)"
                        },
                        new
                        {
                            Id = 5,
                            CaloriesBurnedPerMinute = 6.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 3,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 6,
                            CaloriesBurnedPerMinute = 6.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 3,
                            Name = "Bent Over Row (Barbell)"
                        },
                        new
                        {
                            Id = 4,
                            CaloriesBurnedPerMinute = 8.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 3,
                            Name = "Pull-Up (Barfiks)"
                        },
                        new
                        {
                            Id = 28,
                            CaloriesBurnedPerMinute = 6.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 3,
                            Name = "Seated Cable Row"
                        },
                        new
                        {
                            Id = 29,
                            CaloriesBurnedPerMinute = 6.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 3,
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = 12,
                            CaloriesBurnedPerMinute = 6.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 5,
                            Name = "Overhead Press (Military Press)"
                        },
                        new
                        {
                            Id = 13,
                            CaloriesBurnedPerMinute = 4.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 5,
                            Name = "Dumbbell Lateral Raise"
                        },
                        new
                        {
                            Id = 30,
                            CaloriesBurnedPerMinute = 5.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 5,
                            Name = "Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = 31,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 5,
                            Name = "Front Raise (Dumbbell / Barbell)"
                        },
                        new
                        {
                            Id = 32,
                            CaloriesBurnedPerMinute = 4.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 5,
                            Name = "Face Pull (Kablo)"
                        },
                        new
                        {
                            Id = 33,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 5,
                            Name = "Reverse Fly (Dumbbell / Makine)"
                        },
                        new
                        {
                            Id = 8,
                            CaloriesBurnedPerMinute = 8.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 4,
                            Name = "Squat (Barbell)"
                        },
                        new
                        {
                            Id = 9,
                            CaloriesBurnedPerMinute = 7.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 4,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 34,
                            CaloriesBurnedPerMinute = 7.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 4,
                            Name = "Romanian Deadlift (RDL)"
                        },
                        new
                        {
                            Id = 35,
                            CaloriesBurnedPerMinute = 5.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 4,
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = 10,
                            CaloriesBurnedPerMinute = 7.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 4,
                            Name = "Lunge (Dumbbell)"
                        },
                        new
                        {
                            Id = 11,
                            CaloriesBurnedPerMinute = 5.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 4,
                            Name = "Lying Leg Curl"
                        },
                        new
                        {
                            Id = 14,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 6,
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = 36,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 6,
                            Name = "Hammer Curl (Dumbbell)"
                        },
                        new
                        {
                            Id = 37,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 6,
                            Name = "Preacher Curl"
                        },
                        new
                        {
                            Id = 15,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 6,
                            Name = "Triceps Pushdown (Kablo)"
                        },
                        new
                        {
                            Id = 38,
                            CaloriesBurnedPerMinute = 4.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 6,
                            Name = "Skull Crusher"
                        },
                        new
                        {
                            Id = 39,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 6,
                            Name = "Overhead Triceps Extension (Dumbbell)"
                        },
                        new
                        {
                            Id = 17,
                            CaloriesBurnedPerMinute = 4.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 7,
                            Name = "Crunch (Mekik)"
                        },
                        new
                        {
                            Id = 16,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 7,
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 40,
                            CaloriesBurnedPerMinute = 5.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 7,
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = 41,
                            CaloriesBurnedPerMinute = 4.5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 7,
                            Name = "Russian Twist"
                        },
                        new
                        {
                            Id = 42,
                            CaloriesBurnedPerMinute = 4.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 7,
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = 43,
                            CaloriesBurnedPerMinute = 5.0,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 7,
                            Name = "Ab Wheel Rollout"
                        },
                        new
                        {
                            Id = 18,
                            CaloriesBurnedPerMinute = 11.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Koşu"
                        },
                        new
                        {
                            Id = 19,
                            CaloriesBurnedPerMinute = 9.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Bisiklet"
                        },
                        new
                        {
                            Id = 20,
                            CaloriesBurnedPerMinute = 10.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Kürek (Rowing)"
                        },
                        new
                        {
                            Id = 21,
                            CaloriesBurnedPerMinute = 12.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "İp Atlama"
                        },
                        new
                        {
                            Id = 22,
                            CaloriesBurnedPerMinute = 5.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Yürüyüş"
                        },
                        new
                        {
                            Id = 23,
                            CaloriesBurnedPerMinute = 10.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Yüzme"
                        },
                        new
                        {
                            Id = 24,
                            CaloriesBurnedPerMinute = 8.0,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MuscleGroup = 8,
                            Name = "Eliptik"
                        });
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("CaloriesPer100g")
                        .HasColumnType("float");

                    b.Property<double>("CarbsPer100g")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("FatPer100g")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("ProteinPer100g")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.KnowledgeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeEntries");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.NutritionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmountGrams")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId", "LoggedAt");

                    b.ToTable("NutritionLogs");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentWeightKg")
                        .HasColumnType("float");

                    b.Property<int>("DailyCalorieGoal")
                        .HasColumnType("int");

                    b.Property<int>("DailyProteinGoal")
                        .HasColumnType("int");

                    b.Property<int>("DailyWaterGoalMl")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("GoalType")
                        .HasColumnType("int");

                    b.Property<double>("HeightCm")
                        .HasColumnType("float");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<double?>("TargetWeightKg")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WaterLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountMl")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LoggedAt");

                    b.ToTable("WaterLogs");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WeightEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("WeightEntries");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CaloriesBurned")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId", "PerformedAt");

                    b.ToTable("WorkoutLogs");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutPlanDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId", "DayIndex")
                        .IsUnique();

                    b.ToTable("WorkoutPlanDays");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutPlanExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkoutPlanDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutPlanDayId");

                    b.ToTable("WorkoutPlanExercises");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.BodyMeasurement", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.DietitianClient", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitMetrics.Domain.Entities.User", "Dietitian")
                        .WithMany()
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Dietitian");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.NutritionLog", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.Food", "Food")
                        .WithMany("NutritionLogs")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitMetrics.Domain.Entities.User", "User")
                        .WithMany("NutritionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WaterLog", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WeightEntry", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.User", "User")
                        .WithMany("WeightEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutLog", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.Exercise", "Exercise")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitMetrics.Domain.Entities.User", "User")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutPlan", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutPlanDay", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.WorkoutPlan", "WorkoutPlan")
                        .WithMany("Days")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutPlanExercise", b =>
                {
                    b.HasOne("FitMetrics.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitMetrics.Domain.Entities.WorkoutPlanDay", "Day")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutPlanDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("WorkoutLogs");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.Food", b =>
                {
                    b.Navigation("NutritionLogs");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.User", b =>
                {
                    b.Navigation("NutritionLogs");

                    b.Navigation("WeightEntries");

                    b.Navigation("WorkoutLogs");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutPlan", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("FitMetrics.Domain.Entities.WorkoutPlanDay", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
